server:
  port: 8085
  
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/sms_db
      username: root
      password: Tiger2143@+%
      
  jpa:
    hibernate:
        ddl-auto: create
    show-sql: true
    properties:
        hibernate:
           format_sql: true 
         